### PR TITLE
Added NBT Editing tools

### PR DESCRIPTION
**Pull request by Shreyanshnarwe1**
Added New Section (NBT Editors), Because the  "How to Edit NBT Safely" page linked to this page, which did not have any nbt editors.

### CODE REVIEW

**Comment by Fabrimat** [comment]
I think that [NBT Studio](https://github.com/tryashtar/nbt-studio) is also worth a mention.

**Comment by Shreyanshnarwe1** [comment]
@Fabrimat Yep gotta check it out

**Comment by Shreyanshnarwe1** [comment]
@Fabrimat I can't find a suitable description for it, will look into it later!

**Comment by Shreyanshnarwe1** [comment]
i think i kinda messed up with the files...
cya!

**Pull request closed without merging**
